[package]
name = "database_adapters"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1.88"
tokio = "1.45.1"
tokio-postgres = {workspace = true}
serde = { workspace = true }