[package]
name = "foundry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = { workspace = true }
serde = { workspace = true}
serde_yaml = { workspace = true }
minijinja = {version = "2.10.2"}
tempfile = "3.20.0"