services:
  source_db:
    build:
      context: dvdrental
      args:
        HTTP_PROXY: http://host.docker.internal:9000
        HTTPS_PROXY: http://host.docker.internal:9000
        NO_PROXY: localhost,127.0.0.1,.local,host.docker.internal,*.docker.internal,172.17.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    container_name: dvdrental-source-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dvdrental
    ports:
      - "15432:5432"
    networks:
      - example-net

  kafka-broker:
    image: apache/kafka:latest
    container_name: kafka-broker
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:19092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka-broker:19092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      KAFKA_NUM_PARTITIONS: "3"
    ports:
      - "9092:9092"
    networks:
      - example-net

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.7.1
    container_name: kafka-connect
    depends_on:
      - kafka-broker
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka-broker:19092
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components,/opt/kafka/plugins
      CONFLUENT_PLUGINS_INSTALL: confluentinc/kafka-connect-jdbc:latest
    ports:
      - "8083:8083"
    volumes:
      - ./connect_plugins:/opt/kafka/plugins
      - kafka-connect-data:/var/lib/kafka-connect
    networks:
      - example-net

  kafbat:
    image: kafbat/kafka-ui:latest
    container_name: kafbat-ui
    depends_on:
      - kafka-broker
    environment:
      KAFKA_CLIENT_ID: kafbat-ui
      KAFKA_CLUSTERS_0_NAME: Local Cluster
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-broker:19092
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:19092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: Local Connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083
    ports:
      - "8081:8080"
    networks:
      - example-net

  dpf:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: http://host.docker.internal:9000
        HTTPS_PROXY: http://host.docker.internal:9000
        NO_PROXY: localhost,127.0.0.1,.local,host.docker.internal,*.docker.internal,172.17.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    container_name: dpf
    environment:
      CARGO_HOME: /home/vscode/.cargo
      CARGO_TARGET_DIR: /home/vscode/.cargo/target
    networks:
      - example-net
    volumes:
      - ../..:/workspace:cached

volumes:
  kafka-connect-data:

networks:
  example-net:
    name: example-net
    driver: bridge
