[package]
name = "logging"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "ansi"] }
chrono = { version = "0.4.41", features = ["std"] }
